- name: Pull backend image
  docker_image:
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"
    source: pull
    force: no

- name: Run backend container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}:{{ image_tag }}"
    state: started
    ports:
      - "{{ host_port }}:{{ container_port }}"
    restart_policy: unless-stopped
